### PR TITLE
v1.2.1

### PR DESCRIPTION
**Pull request by prjemian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin All tests pass.  Ready to review and publish.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Review by mrakitin — APPROVED** [review]
Looks great! Thanks for the efforts, @prjemian!

**Comment by prjemian** [comment]
@mrakitin - Thanks!  No harm in checking the rendering.  (I did it locally.  I keep a `smithy` environment for that work.)

**Comment by mrakitin** [comment]
Same on my end; I just did not notice #14 before I asked to rerender.

**Pull request merged**
