### PR TITLE
include py3.12

### PR DESCRIPTION
**Pull request by prjemian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by prjemian** [comment]
@mrakitin How do we get this to include Py3.12?

**Comment by prjemian** [comment]
- https://github.com/conda-forge/hklpy-feedstock/pull/15

**Comment by mrakitin** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base/#migrators-and-migrations

**Comment by prjemian** [comment]
@mrakitin **How** did you find that?

**Comment by mrakitin** [comment]
I knew there was documentation on migrators somewhere, went to the docs and found it.

**Comment by mrakitin** [comment]
@prjemian, what's the blocker here?

**Comment by prjemian** [comment]
@mrakitin -- Time.

**Comment by prjemian** [comment]
On examination, I should not have closed #14.  I'll ask the admins to run the bot again.  Looks like the proposed commits would solve the problem I see now.

**Comment by prjemian** [comment]
The migration process involves making a PR to the conda-forge-pinning-feedstock to address a situation where the regro-cf-autotick-bot has not yet proposed a migration.  That's not the case here, as demonstrated by the commits proposed initially in PR #13.

**Comment by prjemian** [comment]
If the regro bot proposes changes including Py3.12 builds, I'll approve it and cancel this PR.

**Comment by prjemian** [comment]
- #14

**Pull request closed without merging**
